Repository mergifyio-testing/functional-testing-repo-sileht, pull requests merged in 2021-09, with the labels that each got.

#520 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#521 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#532 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#542 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#543 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#552 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#553 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#561 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#562 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#571 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#572 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#580 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#581 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#589 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#590 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#598 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#599 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#607 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#608 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#616 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#617 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#625 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#626 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#634 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#635 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#714 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#715 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#723 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#724 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#772 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#795 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#805 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#806 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#848 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#849 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#857 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#858 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#871 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#872 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#880 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#881 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#894 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#916 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#917 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#925 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#926 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#934 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#935 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#943 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#944 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#961 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#962 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#970 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#971 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#994 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#995 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1003 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1004 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1012 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1013 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1035 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1036 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1073 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1074 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1082 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1083 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1091 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1092 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1100 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1101 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1109 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1110 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1118 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1119 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1127 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1128 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1136 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1137 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1146 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1147 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1155 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1156 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1172 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1173 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1181 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1182 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1198 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#1208 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#1230 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#1246 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1247 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1255 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1256 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1325 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1326 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1334 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1335 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1344 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#1427 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#1428 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#1434 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#1437 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#1442 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#1449 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1450 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1458 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1459 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1479 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#1490 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#1516 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#1701 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1702 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1717 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#1813 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#1814 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#1820 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#1823 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#1828 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#1833 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1834 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1842 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1843 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1859 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#1869 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#1891 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent
