Repository mergifyio-testing/functional-testing-repo-sileht, pull requests merged in 2021-10, with the labels that each got.

#2004 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#2007 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#2012 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#2013 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#2014 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#2022 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#2023 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#2029 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#2032 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#2039 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#2060 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#2067 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#2142 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#2143 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#2175 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#2193 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#2244 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#2259 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#2287 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#2350 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#2375 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#2441 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#2596 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent
