Repository mergifyio-testing/functional-testing-repo-sileht, pull requests merged in 2021-08, with the labels that each got.

#5 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#8 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#13 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#18 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#19 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#27 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#28 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#44 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#54 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#79 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#242 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#243 test_merge_priority: pull request n2 from fork
  test2
Labels: medium
