Repository mergifyio-testing/functional-testing-repo-sileht, pull requests merged in 2022-05, with the labels that each got.

#8134 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#8145 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#8170 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#8197 test_queue_freeze_with_pr_just_about_to_merge: pull request n2 from fork
  test2
Labels: queue-urgent

#8199 test_queue_freeze_with_pr_just_about_to_merge: pull request n2 from fork
  test2
Labels: queue-urgent

#8253 test_queue_fast_forward: pull request n1 from fork
  test1
Labels: queue

#8272 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#8273 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8293 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#8304 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#8324 test_queue_fast_forward: pull request n1 from fork
  test1
Labels: queue

#8341 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#8366 test_create_queue_freeze: pull request n2 from fork
  test2
Labels: queue-urgent

#8391 test_rebase_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge

#8393 test_rebase_on_uptodate_pr_branch: pull request n1 from fork
  test1
Labels: merge

#8395 test_rebase_on_uptodate_pr_branch: pull request n1 from fork
  test1
Labels: merge

#8397 test_rebase_on_uptodate_pr_branch: pull request n1 from fork
  test1
Labels: merge

#8399 test_update_action: pull request n1 from fork
  test1
Labels: merge

#8401 test_update_action_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge

#8489 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#8490 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8499 test_batch_split_with_no_speculative_checks: pull request n1 from fork
  test1
Labels: queue

#8530 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#8649 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#8650 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8658 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#8659 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8668 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8773 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#8774 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8782 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#8783 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8792 test_batch_split_with_no_speculative_checks: pull request n1 from fork
  test1
Labels: queue

#8812 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#8823 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#8829 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#8853 test_queue_fast_forward: pull request n1 from fork
  test1
Labels: queue

#8883 test_queue_fast_forward: pull request n1 from fork
  test1
Labels: queue

#8916 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#8917 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#8966 test_ongoing_train_basic: pull request n1 from fork
  test1
Labels: queue

#9003 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#9009 test_queue_cancel_and_refresh: pull request n1 from fork
  test1
Labels: queue

#9102 test_queue_priority: pull request n3 from fork
  test3
Labels: queue-urgent

#9187 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9190 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9193 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9196 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9199 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9202 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9205 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9208 test_queue_with_rebase_update_method: pull request n1 from fork
  test1
Labels: queue

#9274 test_speculative_checks_fastforward: pull request n1 from origin
  test2
  test2-moved
Labels: queue

#9283 test_speculative_checks_fastforward: pull request n1 from origin
  test2
  test2-moved
Labels: queue

#9294 test_speculative_checks_fastforward: pull request n1 from origin
  test1
Labels: queue

#9301 test_speculative_checks_fastforward: pull request n1 from origin
  test1
Labels: queue

#9308 test_speculative_checks_fastforward: pull request n1 from origin
  test1
Labels: queue

#9310 test_speculative_checks_fastforward: pull request n3 from origin
  test3
Labels: queue

#9311 test_speculative_checks_fastforward: pull request n4 from origin
  test4
Labels: queue

#9336 test_queue_freeze_with_pr_just_about_to_merge: pull request n2 from fork
  test2
Labels: queue-urgent

#9353 test_rebase_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge

#9355 test_rebase_on_closed_pr_deleted_branch: pull request n1 from fork
  test1
Labels: merge

#9357 test_rebase_on_uptodate_pr_branch: pull request n1 from fork
  test1
Labels: merge

#9360 test_create_queue_freeze: pull request n2 from fork
  test2
Labels: queue-urgent

#9364 test_queue_freeze_with_pr_just_about_to_merge: pull request n2 from fork
  test2
Labels: queue-urgent

#9366 test_queue_freeze_with_pr_just_about_to_merge: pull request n2 from fork
  test2
Labels: queue-urgent
