Repository mergifyio-testing/functional-testing-repo-sileht, pull requests merged in 2023-03, with the labels that each got.

#30266 test_rebase_on_closed_pr_deleted_branch: pull request n1 from admin
  test1
Labels: merge

#30268 test_rebase_on_uptodate_pr_branch: pull request n1 from admin
  test1
Labels: merge

#30309 test_rebase_on_closed_pr_deleted_branch: pull request n1 from admin
  test1
Labels: merge

#30311 test_rebase_on_uptodate_pr_branch: pull request n1 from admin
  test1
Labels: merge

#30492 test_queue_cancel_and_refresh: pull request n1 from admin
  test1
Labels: queue

#30577 test_queue_cancel_and_refresh: pull request n1 from admin
  test1
Labels: queue

#30587 test_queue_cancel_and_refresh: pull request n1 from admin
  test1
Labels: queue

#30767 test_queue_cancel_and_refresh: pull request n1 from admin
  test1
Labels: queue

#30884 test_queue_fast_forward: pull request n1 from admin
  test1
Labels: queue

#30953 Create TOTO
  TOTO
Labels: toto
